// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyB3_-RPbf14HjrblL_cPi3RnTBMsyNW9m4',
  //   appId: '1:2586065989:web:a216bfb6c95a223992b72c',
  //   messagingSenderId: '2586065989',
  //   projectId: 'escaping',
  //   authDomain: 'escaping.firebaseapp.com',
  //   storageBucket: 'escaping.appspot.com',
  //   measurementId: 'G-TNP7VH15JZ',
  // );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyAybEOR9vnKO0ktjjRwp6GJ3h8WxpZsVec',
  //   appId: '1:2586065989:android:5051b280b74a940892b72c',
  //   messagingSenderId: '2586065989',
  //   projectId: 'escaping',
  //   storageBucket: 'escaping.appspot.com',
  // );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDptLudO6cE2VpcXjN-oHizYK0Iwn1ut6g',
    appId: '1:1002977013267:android:fa4726eae86551196a19e6',
    messagingSenderId: '1002977013267',
    projectId: 'escaping-plan',
    storageBucket: 'escaping-plan.appspot.com',
  );
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyD22nNMG9sk3lUp3wLm9FrDnE-UZEdWj24',
  //   appId: '1:2586065989:ios:9d2872f6d2be728192b72c',
  //   messagingSenderId: '2586065989',
  //   projectId: 'escaping',
  //   storageBucket: 'escaping.appspot.com',
  //   iosBundleId: 'com.escapingplan',
  // );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9u0ScgpCVW3F8RBVi69PEsNOTSmpAiqw',
    appId: '1:1002977013267:ios:1f601dcda2ee7b196a19e6',
    messagingSenderId: '1002977013267',
    projectId: 'escaping-plan',
    storageBucket: 'escaping-plan.appspot.com',
    iosBundleId: 'com.escapingplan',
  );
  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyD22nNMG9sk3lUp3wLm9FrDnE-UZEdWj24',
  //   appId: '1:2586065989:ios:5d05443c8e304c9392b72c',
  //   messagingSenderId: '2586065989',
  //   projectId: 'escaping',
  //   storageBucket: 'escaping.appspot.com',
  //   iosBundleId: 'com.escapingplan.escapingplan',
  // );
}
//
